### ISSUE TITLE
Pre-Compiled Binary

### ISSUE THREAD

**Issue by KevinFumbles** [Alexander-r/gosrvmon#1]
Hi, I was looking into this project but, I noticed it doesn’t have any releases. I’m not familiar with compiling Go, so I hoping you’d be able to help me out. What’s the best method for getting the binary on my machine so I can set up a systemd service? Personally, I’d rather not use docker, but that was the only method I saw on the README.
Thanks!

**Comment by Alexander-r** [comment]
If you have go sdk installed then you can build the project using:
```go get github.com/Alexander-r/gosrvmon```
The resulting binary will be located at ```$GOPATH/bin/gosrvmon```
But I just noticed that at the moment it will not work with go 1.16 as I have not set up modules for that. I will fix it when I have some time.
For github releases I will also look into github actions acd check if I can use it.

Right now the project has a mirror at gitlab and it has CI set up there. You can download the binary from pipeline artifacts there (download artifacts button on the right next to the pipeline):
https://gitlab.com/Sonnix/gosrvmon/-/pipelines

For the current version the binary will be at:
https://gitlab.com/Sonnix/gosrvmon/-/jobs/1078861274/artifacts/file/gosrvmon

That binary is for Linux (it is built with CGO_ENABLED=0 and is not linked to libc so it should work on most distributions). The project can also be built for Windows and Mac OS. I will update the documentation on that once I fix the modules for go 1.16.

The project has an example systemd unit file at https://github.com/Alexander-r/gosrvmon/blob/master/gosrvmon.service
